# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='test_service.proto',
  package='zros_example',
  syntax='proto3',
  serialized_pb=_b('\n\x12test_service.proto\x12\x0czros_example\"3\n\x12TestServiceRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0e\n\x06\x64\x65tail\x18\x02 \x01(\t\"%\n\x13TestServiceResponse\x12\x0e\n\x06\x64\x65tail\x18\x01 \x01(\tb\x06proto3')
)




_TESTSERVICEREQUEST = _descriptor.Descriptor(
  name='TestServiceRequest',
  full_name='zros_example.TestServiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='zros_example.TestServiceRequest.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='detail', full_name='zros_example.TestServiceRequest.detail', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=87,
)


_TESTSERVICERESPONSE = _descriptor.Descriptor(
  name='TestServiceResponse',
  full_name='zros_example.TestServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail', full_name='zros_example.TestServiceResponse.detail', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['TestServiceRequest'] = _TESTSERVICEREQUEST
DESCRIPTOR.message_types_by_name['TestServiceResponse'] = _TESTSERVICERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestServiceRequest = _reflection.GeneratedProtocolMessageType('TestServiceRequest', (_message.Message,), dict(
  DESCRIPTOR = _TESTSERVICEREQUEST,
  __module__ = 'test_service_pb2'
  # @@protoc_insertion_point(class_scope:zros_example.TestServiceRequest)
  ))
_sym_db.RegisterMessage(TestServiceRequest)

TestServiceResponse = _reflection.GeneratedProtocolMessageType('TestServiceResponse', (_message.Message,), dict(
  DESCRIPTOR = _TESTSERVICERESPONSE,
  __module__ = 'test_service_pb2'
  # @@protoc_insertion_point(class_scope:zros_example.TestServiceResponse)
  ))
_sym_db.RegisterMessage(TestServiceResponse)


# @@protoc_insertion_point(module_scope)
